uint64 timestamp # time since system start (microseconds)

uint32 mode # for ACTION_SWITCH_MODE what mode is requested according to commander_state.MAIN_STATE_
uint32 state

float32 sweep_time_segment_pct # sweep time frequency percentage
float32 sweep_frequency
float32 sweep_amplitude

float32 doublet_amplitude

float32 injection_input
float32 injection_output

float32 raw_output
float32 injection_point
