language: cpp

git:
  depth: 100
  submodules: false

matrix:
  fast_finish: true
  include:
    - env: BUILD_TARGET=coverity_scan
      if: branch = coverity_scan
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
    - export PATH=$HOME/.local/bin:$PATH
    - pip install --user --upgrade pip
    - pip install --user -r Tools/setup/requirements.txt

script:
    - make

addons:
  coverity_scan:
    project:
      name: "PX4/Firmware"
      description: "Build submitted via Travis CI"
    notification_email: ci@px4.io
    build_command_prepend: "make distclean"
    build_command: "make posix_sitl_default"
    branch_pattern: coverity_scan
