sudo: required
language: cpp
python:
- '3.5'
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - MATRIX_EVAL=""
    - os: linux
      dist: trusty
      compiler: clang
      env:
        - CC=clang CXX=clang++
        - MATRIX_EVAL=""
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - RUN_PYTEST=1
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install -y clang cmake g++ gcc libeigen3-dev swig3.0 python-dev gcc-5 g++-5
  - eval "${MATRIX_EVAL}"
  - if [ -n "${RUN_PYTEST}" ]; then pip3 install -r ./EKF/tests/pytest/requirements.txt; fi

script: ./build.sh
