language: cpp
os: linux
dist: trusty

python:
  - '3.5'

addons:
  apt:
    packages:
     - clang
     - cmake
     - libeigen3-dev
     - python-dev
     - swig3.0

matrix:
  fast_finish: true
  include:
    - compiler: gcc
    - compiler: clang
      env: CC=clang CXX=clang++
    - env: RUN_PYTEST=1
  allow_failures:
    - env: RUN_PYTEST=1


before_install:
  - if [ -n "${RUN_PYTEST}" ]; then
      pip install --user -r ./EKF/tests/pytest/requirements.txt;
    fi

script: ./build.sh
