# Build version
version: "{build}"

# Build worker image (build VM template)
image: Visual Studio 2017

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform:
- x64

# scripts that are called at very beginning, before repo cloning
init:
- ver

install:
- ps: if (-not (Test-Path C:\Toolchain.msi)) {Invoke-WebRequest https://s3-us-west-2.amazonaws.com/px4-tools/PX4+Windows+Cygwin+Toolchain/PX4+Windows+Cygwin+Toolchain+0.3.msi -OutFile C:\Toolchain.msi}
- start /wait msiexec /i C:\Toolchain.msi /quiet /qn /norestart /log C:\install.log

build_script:
- call C:\PX4\toolchain\clone-px4-build-sitl.bat

cache:
- C:\Toolchain.msi
