codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 5
    wait_for_ci: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        only_pulls: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: yes

ignore:
  - "src/examples"
  - "src/modules/attitude_estimator_q"
  - "src/modules/local_position_estimator"
