name: C/C++ CI

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    strategy:
      matrix:
        container: [
          "px4io/px4-dev-base-bionic:2020-03-28",
          "px4io/px4-dev-base-focal:2020-03-28"
          ]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: make
      run: make
