name: compile nuttx

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-nuttx:2019-10-24
    strategy:
      matrix:
        config: [
          px4_io-v2_default,
          px4_fmu-v2_default, px4_fmu-v2_fixedwing, px4_fmu-v2_lpe, px4_fmu-v2_multicopter, px4_fmu-v2_rover, px4_fmu-v2_test,
          px4_fmu-v3_default,
          px4_fmu-v4_default,
          px4_fmu-v4pro_default,
          px4_fmu-v5_default, px4_fmu-v5_fixedwing, px4_fmu-v5_multicopter, px4_fmu-v5_rover, px4_fmu-v5_rtps, px4_fmu-v5_stackcheck,
          px4_fmu-v5x_default,
          airmind_mindpx-v2_default, auav_x21_default, av_x-v1_default, bitcraze_crazyflie_default,
          holybro_kakutef7, holybro_durandal-v1_default, holybro_durandal-v1_stackcheck,
          intel_aerofc-v1_default, modalai_fc-v1_default, mro_ctrl-zero-f7_default, nxp_fmuk66-v3_default, omnibus_f4sd_default, uvify_core_default
          ]
    steps:
    - uses: actions/checkout@v1
    - name: make ${{ matrix.config }}
      run: make ${{ matrix.config }}
