
name: EKF Build Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Linux-GCC:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-focal:2021-05-04
    steps:
    - uses: actions/checkout@v1
    - name: main build
      run: make
      working-directory: src/lib/ecl
    - name: clean build
      run: make clean
      working-directory: src/lib/ecl
    - name: main test
      run: make test
      working-directory: src/lib/ecl
  Linux-Clang:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-clang:2021-05-04
    env:
      CC: clang
      CXX: clang++
    steps:
      - uses: actions/checkout@v1
      - name: main build
        run: make
        working-directory: src/lib/ecl
      - name: clean build
        run: make clean
        working-directory: src/lib/ecl
      - name: main test
        run: make test
        working-directory: src/lib/ecl
  Mac-OS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: main build
        run: make
        working-directory: src/lib/ecl
      - name: clean build
        run: make clean
        working-directory: src/lib/ecl
      - name: main test
        run: make test
        working-directory: src/lib/ecl
