name: Change Indicator

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-focal:2020-09-14
    steps:
    - uses: actions/checkout@v1
    - name: main test
      run: make test
    - name: Check if there exists diff
      run: git diff --exit-code
      working-directory: test/change_indication
