name: Hardware Linux

on:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: [emlid_navio2]
    steps:
    - uses: actions/checkout@v1

    - name: Build
      env:
        CCACHE_BASEDIR: ${GITHUB_WORKSPACE}
      run: |
          make distclean
          ccache -z
          make emlid_navio2_default
          ccache -s

    # sanity check
    - name: Sanity check
      run: cd build/emlid_navio2_default/ && ./bin/px4 -s ../../posix-configs/rpi/px4_test.config

    - name: Upload log to flight review
      run: find . -name *.ulg
      #run: ./Tools/upload_log.py -q --description "${GITHUB_WORKFLOW} ${GITHUB_RUN_ID}" --feedback "${GITHUB_WORKFLOW} ${GITHUB_RUN_ID} ${GITHUB_REPOSITORY} ${GITHUB_REF}" --source CI ./build/px4_sitl_default/tmp/rootfs/log/*/*.ulg
