name: Python CI checks

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Install tools
      run: sudo apt-get install python-setuptools flake8 mypy -y
    - name: Check MAVSDK test scripts with mypy
      run: mypy --strict test/mavsdk_tests/*.py
    - name: Check MAVSDK test scripts with flake8
      run: flake8 test/mavsdk_tests/*.py
