name: SITL Tests (Code Coverage)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-simulation-bionic:2019-12-18
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Set Python 3 as default
      run: update-alternatives --install /usr/bin/python python /usr/bin/python3 10
    - name: Install psutil
      run: pip3 install psutil
    - name: Run simulation tests
      run: make tests_integration_coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: mavsdk
